{{- $auth := printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry (printf "%s:%s" .Values.username .Values.password | b64enc) | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: registrycreds
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $auth }}
